import './tokens/tokens.css';
import './tokens/typography.css';
import './tokens/motion.css';
import './theme/theme.css';
import './motion/motion.css';
import { initTheme } from './theme/theme';
import './components/button/index.js';
import './components/card/index.js';
import './components/heading/index.js';
import './components/text/index.js';
import './components/icon/index.js';
import './components/container/index.js';
initTheme();
